"""Export a finished tour.

Three renderings of the same content, none of which may add a fact that the
grounding gate did not already accept:

- `.tour` — the executable one. CodeTour opens it inside VS Code at the right
  line, which is the whole point of the project: a reader follows the path in
  the editor instead of reading another web page about the code.
- `ONBOARDING.md` — the same path for people who do not use VS Code.
- `architecture.mmd` — the stations and the real import edges between them.

Everything here is a pure function of a `Tour`. Nothing reads the filesystem,
nothing calls a model, and rendering the same tour twice produces identical
bytes — the tour is meant to be reproducible from a commit, so its exports
have to be too.
"""

from __future__ import annotations

import json
from dataclasses import dataclass

from .explanation import Provenance, StationExplanation
from .stations import LAYER_ORDER

CODETOUR_SCHEMA = "https://aka.ms/codetour-schema"

# Every generated file carries this string. `generate` writes into the
# repository root, where a hand-written ONBOARDING.md may already live, and
# silently overwriting someone's own documentation would be unforgivable — so
# a file without this marker is never overwritten without --force.
MARKER = "Generated by RepoOnboard"


def is_generated(content: str) -> bool:
    """True when a file was written by this tool and is safe to replace."""
    return MARKER in content


@dataclass(frozen=True)
class TourStation:
    """One station, ready to render."""

    path: str
    layer: str
    anchor_line: int
    explanation: StationExplanation


@dataclass(frozen=True)
class Tour:
    """Everything the exporters need, and nothing else."""

    repository: str
    commit: str | None
    stations: tuple[TourStation, ...]
    edges: tuple[tuple[str, str], ...] = ()
    resolution_rate: float | None = None


# ---------------------------------------------------------------------------
# .tour — CodeTour
# ---------------------------------------------------------------------------


def _step_description(station: TourStation) -> str:
    explanation = station.explanation
    parts = [explanation.summary, "", f"**Why this file matters:** {explanation.why_it_matters}"]

    parts.extend(["", "**Check yourself:**", ""])
    for index, question in enumerate(explanation.questions, start=1):
        location = question.answer_location
        span = (
            f"line {location.start_line}"
            if location.start_line == location.end_line
            else f"lines {location.start_line}-{location.end_line}"
        )
        parts.append(f"{index}. {question.prompt}")
        parts.append(f"   *Answer: {location.path}, {span}.*")

    if explanation.provenance is Provenance.STRUCTURAL:
        parts.extend(
            [
                "",
                (
                    "> This station was written without a language model. It "
                    "describes what the file contains rather than what it is for."
                ),
            ]
        )
    return "\n".join(parts)


def to_codetour(tour: Tour) -> str:
    """Render a `.tour` file.

    `ref` is what makes CodeTour itself aware of staleness: it pins the tour to
    the commit it was generated from, and the extension warns when the working
    tree has moved on.
    """
    steps = []
    for index, station in enumerate(tour.stations, start=1):
        steps.append(
            {
                "file": station.path,
                "line": station.anchor_line,
                "title": f"{index}. {station.path} ({station.layer})",
                "description": _step_description(station),
            }
        )

    document: dict[str, object] = {
        "$schema": CODETOUR_SCHEMA,
        "title": f"Onboarding: {tour.repository}",
        "description": (
            f"{MARKER}. Stations selected and ordered from the dependency graph, "
            "not from a language model's opinion. Every question carries the "
            "location of its answer."
        ),
        "steps": steps,
    }
    if tour.commit:
        document["ref"] = tour.commit

    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# stations.json — the machine-readable record `check` reads back
# ---------------------------------------------------------------------------


def to_json_payload(tour: Tour) -> str:
    """Serialise the tour for `check`.

    Carries the anchor line and layer as well as the prose, because staleness
    is judged against every line the tour sends a reader to — the anchor
    included, not just the answer locations.
    """
    document = {
        "generator": MARKER,
        "repository": tour.repository,
        "commit": tour.commit,
        "stations": [
            {
                "path": station.path,
                "layer": station.layer,
                "anchor_line": station.anchor_line,
                **station.explanation.model_dump(mode="json"),
            }
            for station in tour.stations
        ],
    }
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


# ---------------------------------------------------------------------------
# ONBOARDING.md
# ---------------------------------------------------------------------------

_PROVENANCE_LABEL = {
    Provenance.MODEL: "explained by model, verified",
    Provenance.MODEL_RETRY: "explained by model after one correction, verified",
    Provenance.STRUCTURAL: "structural — no model involved",
}


def _anchor(path: str, start: int, end: int) -> str:
    """A link to the answer, in the line-fragment form GitHub understands."""
    if start == end:
        return f"[`{path}:{start}`]({path}#L{start})"
    return f"[`{path}:{start}-{end}`]({path}#L{start}-L{end})"


def _provenance_sentence(tour: Tour) -> str:
    """State how the prose came to exist, without overclaiming.

    A tour generated with `--dry-run` contains no model output at all, and a
    header that says a model wrote the explanations would be false. The
    sentence is derived from the stations rather than assumed.
    """
    total = len(tour.stations)
    structural = sum(
        1 for station in tour.stations if station.explanation.provenance is Provenance.STRUCTURAL
    )
    if total == 0:
        return "This tour has no stations."
    if structural == total:
        return (
            "No language model was involved. Every station's text was derived "
            "from the code's own structure, so it describes what each file "
            "contains rather than what it is for."
        )
    if structural == 0:
        return (
            "A language model wrote the explanations, and every claim in them was "
            "checked against the code before it was written here."
        )
    return (
        f"A language model wrote {total - structural} of {total} explanations, each "
        f"checked against the code before being written here. The remaining "
        f"{structural} failed that check and fall back to structural text, which "
        "describes what the file contains rather than what it is for."
    )


def to_markdown(tour: Tour) -> str:
    lines = [
        f"<!-- {MARKER}. Do not edit by hand; re-run `repoonboard generate`. -->",
        "",
        f"# Onboarding: {tour.repository}",
        "",
    ]

    if tour.commit:
        lines.append(f"Generated from commit `{tour.commit}`.")
    else:
        lines.append(
            "Generated from a directory with no Git history, so this tour is not "
            "pinned to a commit and cannot be checked for staleness."
        )
    lines.extend(
        [
            "",
            (
                "Stations were selected and ordered from the repository's "
                "dependency graph, never from a language model's opinion."
            ),
            "",
            _provenance_sentence(tour),
            "",
            "## Reading path",
            "",
        ]
    )

    for index, station in enumerate(tour.stations, start=1):
        lines.append(f"{index}. [`{station.path}`](#{index}-{_slug(station.path)}) — {station.layer}")

    for index, station in enumerate(tour.stations, start=1):
        explanation = station.explanation
        lines.extend(
            [
                "",
                "---",
                "",
                f"## {index}. `{station.path}`",
                "",
                (
                    f"**Layer:** {station.layer} · "
                    f"**Opens at line:** {station.anchor_line} · "
                    f"**Provenance:** {_PROVENANCE_LABEL[explanation.provenance]}"
                ),
                "",
                explanation.summary,
                "",
                f"**Why this file matters:** {explanation.why_it_matters}",
                "",
                "### Check yourself",
                "",
            ]
        )
        for number, question in enumerate(explanation.questions, start=1):
            location = question.answer_location
            target = _anchor(location.path, location.start_line, location.end_line)
            lines.append(f"{number}. {question.prompt}")
            lines.append(f"   <br>Answer: {target}")

    lines.append("")
    return "\n".join(lines)


def _slug(path: str) -> str:
    return path.replace("/", "").replace(".", "").replace("_", "").lower()


# ---------------------------------------------------------------------------
# architecture.mmd
# ---------------------------------------------------------------------------


def to_mermaid(tour: Tour) -> str:
    """Render the stations and the import edges that actually exist between them.

    Only direct edges are drawn. A line between two boxes therefore means "this
    file imports that file", not "these are related" — an inferred edge would
    be exactly the kind of unverifiable claim the rest of the tool refuses.
    """
    identifiers = {station.path: f"s{index}" for index, station in enumerate(tour.stations)}

    lines = [f"%% {MARKER}. Do not edit by hand; re-run `repoonboard generate`.", "graph TD"]

    for layer in LAYER_ORDER:
        members = [station for station in tour.stations if station.layer == layer]
        if not members:
            continue
        lines.append(f"    subgraph {layer}")
        for station in members:
            lines.append(f'        {identifiers[station.path]}["{station.path}"]')
        lines.append("    end")

    drawn = {(a, b) for a, b in tour.edges if a in identifiers and b in identifiers}
    for source, target in sorted(drawn):
        lines.append(f"    {identifiers[source]} --> {identifiers[target]}")

    if not drawn:
        lines.append("    %% No direct import edges between the selected stations.")

    return "\n".join(lines) + "\n"
